### ISSUE TITLE
Launcher constantly refreshes

### ISSUE THREAD

**Issue by marcdw1289** [nhirokinet/bluelineconsole#180]
I've been using Blue Line Console as my assist app on my Google-free setups. Really nice. When it became a launcher, gave it a try and got hooked. Fits my minimalist mentality perfectly. Been preparing a write up on it for a certain ROM forum.

I was using v1.2.4 and recently upgraded to v1.2.8. Whenever I exit an app the launcher refreshes every time. For a nanosecond one can see a Refreshing Database dialog/window before the launcher is ready to go.

Didn't have that with 1.2.4. The constant refreshing may be off putting.

EDIT:  This only happens when exiting an app that was launched from BLC. If I go back to the app via Recents/Overview, then exit again, BLC appears instantly as normal.
One has to be super fast to get a screenshot (screen record would be better) but I did catch this one. The text almost disappeared but you can see it when zoomed.

![20211107_010947](https://user-images.githubusercontent.com/42319182/140639431-2a53548a-f427-40a2-86d2-b0048ab97c45.jpg)

**Comment by nhirokinet** [comment]
"Refreshing database" notification  is the behavior what I'm trying to improve.

Basically refresh is done every time the app is launched. But this notification is not displayed if no query is input, so if your device is fast enough to load everything before you type anything, it was rare to see until v1.2.5 except for the first use.

In v1.2.6, contact search functionality was added, and this time the change was made to refresh even in "resume"; "resume" is the time the view is on the top active `Activity` again. This is to make contact search available soon after enabling from `config`.

Since v1.2.8, in home screen mode, if the previous displayed contents is "kept" to default, which means no query, "Refreshing database" not shows up and rewrite the home screen silently.


In your screenshot the query is empty. Can I ask my assumption below is correct?

- You put Blue Line Console as home screen app
- You entered some query, launched some app, and came back to home
- Then the query has got empty again, and "Refreshing database" was there

**Comment by marcdw1289** [comment]
Yes, your assumption is correct.
Thanks for the explanation. I see why it behaves the way it does right now.

**Comment by nhirokinet** [comment]
Thank you, then that does not seem to be unknown problem (but not on GitHub issues yet, so I'll keep this ticket open). I think you can see even if the app is launched from Blue Line Console, if it is opened when the query is empty (by using home screen default command), this does not happen.

Anyway I will try to improve it.

**Comment by nhirokinet** [comment]
Improved the behavior in version 1.2.9.

In this version, when running as home screen, keep previous data displayed and update screen silently after load, as soon as possible. "Refreshing database" in home screen is supposed to be seen only the first time after app start. This is because home app is something passive and refreshing background is natural, and this load is happened if the user even does not touch Blue Line Console.

While running as normal app (with floating window), that is a response to the user's explicit action to Blue Line Console and waiting a bit is natural, and clicking wrong one due to move should be avoided.

Availability on F-droid will take some days for D-droid to build it. (For Google Play, I already uploaded there.)
