### ISSUE TITLE
Weather report

### ISSUE THREAD

**Issue by yephny** [nhirokinet/bluelineconsole#295]
Do you think a weather report would be a good addition to the app? Could use a service like wttr.in.

**Comment by nhirokinet** [comment]
This functionality needs a weather information API service, which means API client should be maintained. Unless there are some named open protocol, maintaining this kind of API might be a little bit heavy for personally maintained launcher.

Blue Line Console already have widget command functionality. I think rather than using some globally provided service, installing local weather service's app and attaching widget as command may be nice because local app can handle locally important information for each region.

**Comment by yephny** [comment]
It completely slipped my mind that Blue Line Console supports widgets. It's perfect for this. Thanks.
