### ISSUE TITLE
Launch the app if it's the only result 

### ISSUE THREAD

**Issue by nikita-bobkov** [nhirokinet/bluelineconsole#314]
It would be nice to have an option that allows to launch an application is this app is the only one in the search result.

It would help to avoid tapping confirm button in many cases.

**Comment by nhirokinet** [comment]
In current behavior, it will be a dangerous option because adding a character not only decrease candidates but sometimes increases.

For example, if "conf" matches only one candidate, then there is no way to access `config` again other than resetting all data in Blue Line Console, as "config" include config but "conf" does not include conf.
