### ISSUE TITLE
[Feature Request] Customizable theme/colors

### ISSUE THREAD

**Issue by jumper047** [nhirokinet/bluelineconsole#47]
Late Android versions have "light/dark theme" feature. It would be great if blueline will change theme according to current system settings.
Also (despite it violates project's name;)) I'll like be able to change accent color (blue lines in upper left and down right corners).
P.S. Great project, I like it!

**Comment by nhirokinet** [comment]
Added dark theme in #52. If OS is set to dark theme, Blue Line Console uses dark theme as default. You can also manually select dark theme (or light theme on dark theme device) by Blue Line Console config.

Accent color, nice, I was wondering what other color may fit as another theme but some OSes can choose accent color. #62 allows to set arbitrary color as accent color from config.

Both were released in version 1.1.0.

**Comment by jumper047** [comment]
Themes are awesome, thank you! Just one minor thing, is it posible to make color picker more user friendly - may be provide list of material colors and keep rgb sliders as option?

**Comment by nhirokinet** [comment]
Improvement of color picker is currently at not so high priority for me, but I will keep in mind that.

Currently UI is placed on one activity and one layout, so if you or someone is trying to improve UI that would be great of course and if someone is discussing on issue before implement so that code can be merged and managed by me, I will comment there.
