### ISSUE TITLE
[Feature Request] When opening the app, you can move it around the screen & the console doesn't disappeared when you use it once.

### ISSUE THREAD

**Issue by puditracode** [nhirokinet/bluelineconsole#51]
it would be nice when you launch the app, you can move it around so then you dont get distracted. and add a setting when you use it once, its not going to get terminated immediately and you have to launch it again.

**Comment by nhirokinet** [comment]
> it would be nice when you launch the app, you can move it around so then you dont get distracted.

I'm now implementing the function to move window by drag and drop. I'm not sure, but is it what you mean on this issue?

> add a setting when you use it once, its not going to get terminated immediately and you have to launch it again

I'm not sure what "terminate" means, but do you mean you want to preserve state after closing and reopening Blue Line Console? If so, can you describe some situations you want that option?

**Comment by nhirokinet** [comment]
The function to move window by drag was released in version 1.2.0.

**Comment by puditracode** [comment]
> > it would be nice when you launch the app, you can move it around so then you dont get distracted.
> 
> I'm now implementing the function to move window by drag and drop. I'm not sure, but is it what you mean on this issue?
> 
> > add a setting when you use it once, its not going to get terminated immediately and you have to launch it again
> 
> I'm not sure what "terminate" means, but do you mean you want to preserve state after closing and reopening Blue Line Console? If so, can you describe some situations you want that option?

Sorry for the late replies.

Imagine in the morning when you just boot your phone up and wanted to open 3 apps without searching them on your phone, instead you use this console to make things faster. For example, you open chrome, the console is still appeared in your screen, then you open another app, and it still there. something like that.

+ You can Add a button arround the console for the user to be able to turn on & off this feature.

Thanks!

**Comment by nhirokinet** [comment]
Do you want the behavior that Blue Line Console opens the app (like Chrome) in background?

If so, I'm afraid this may be impossible under Android system. I think simply there is no API to open Intent background.

The link below is documentation for Activity in Android, and diagram shows Activity lifecycle and states. In this flow after "Activity launched", onCreate(), onStart(), and onResume() seems to be called sequentially. If app can be opened in background, there should be the state between onCreate() and onResume() that developer and user can see.

https://developer.android.com/reference/android/app/Activity

Android is designed to be  secure, so that app can do only what the users desire. One app opening another app background might lead the behavior user does not know, so I don't think this will be implemented on Android in the future.

**Comment by nhirokinet** [comment]
- Launching app background? → Seems impossible (the comment above)
- Blue Line Console coming back after app launch? → Blue Line Console doesn't know the time to come back. And even it knows, at least will disappear once, at least hard to control for user
- Screen overlay instead of normal Activity? → if overlay View can obtain keyboard event, it is too dangerous (it is keylogger without IME privilege) so this should be impossible, although could not find a documentation. And even if possible the app will take the worst manner.

Launching app background does not seem to be possible at all for me

**Comment by nhirokinet** [comment]
Both of 2 are closed, so closing this issue.

> When opening the app, you can move it around the screen

As the commented previously, it is released in version 1.2.0

> the console doesn't disappeared when you use it once

As the comment above, it seems to be impossible
